{{- if .Values.Dep.imageCredentials.enabled }}
{{ range $index, $namespace := (lookup "v1" "Namespace" "" "").items }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.Dep.imageCredentials.secretCreated }}
  namespace: {{ $namespace.metadata.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" $ }}
---
{{- end}}
{{- end}}