package com.imst.event.map.hibernate.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Settings generated by hbm2java
 */
@Entity
@Table(name = "action_state", schema = "public")
public class ActionState implements java.io.Serializable {

	private Integer id;
	private String stateType;
	private String description;
	private Set<BlackList> blackLists = new HashSet<BlackList>(0);

	public ActionState() {
		
	}
	
	public ActionState(Integer id, String stateType, String description, Set<Event> events, Set<BlackList> blackList) {
		super();
		this.id = id;
		this.stateType = stateType;
		this.description = description;
		this.blackLists = blackList;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "description", length = 2048)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "state_type", nullable = false)
	public String getStateType() {
		return stateType;
	}

	public void setStateType(String stateType) {
		this.stateType = stateType;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actionState")
	public Set<BlackList> getBlackLists() {
		return this.blackLists;
	}

	public void setBlackLists(Set<BlackList> blackLists) {
		this.blackLists = blackLists;
	}

	

}
