package com.imst.event.map.hibernate.entity;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AlertState generated by hbm2java
 */
@Entity
@Table(name = "alert_state", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "db_name"))
public class AlertState implements java.io.Serializable {

	private Integer id;
	private String dbName;
	private Integer lastId;
	private Timestamp createDate;
	private Timestamp updateDate;

	public AlertState() {
	}

	public AlertState(String dbName, Integer lastId) {
		this.dbName = dbName;
		this.lastId = lastId;
	}

	public AlertState(String dbName, Integer lastId, Timestamp createDate, Timestamp updateDate) {
		this.dbName = dbName;
		this.lastId = lastId;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "db_name", unique = true, nullable = false, length = 64)
	public String getDbName() {
		return this.dbName;
	}

	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	@Column(name = "last_id", nullable = false)
	public Integer getLastId() {
		return this.lastId;
	}

	public void setLastId(Integer lastId) {
		this.lastId = lastId;
	}

	@Column(name = "create_date", length = 29)
	@org.hibernate.annotations.ColumnDefault("now()")
	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_date", length = 29)
	public Timestamp getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Timestamp updateDate) {
		this.updateDate = updateDate;
	}

}
