package com.imst.event.map.hibernate.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BlackList generated by hbm2java
 */
@Entity
@Table(name = "black_list", schema = "public")
public class BlackList implements java.io.Serializable {

	private Integer id;
	private Layer layer;
	private EventGroup eventGroup;
	private EventType eventType;
	private String name;
	private String createUser;
	private Timestamp createDate;
	private Timestamp updateDate;
	private String tag;
	private State state;
	private ActionState actionState;
	private Timestamp actionDate;
	private Set<EventBlackList> eventBlackLists = new HashSet<EventBlackList>(0);

	public BlackList() {
	}



	public BlackList(Integer id, Layer layer, EventGroup eventGroup, EventType eventType, String name, String createUser, Timestamp createDate, Timestamp updateDate, String tag, 
			State state, ActionState actionState, Timestamp actionDate, Set<EventBlackList> eventBlackLists ) {
		super();
		this.id = id;
		this.layer = layer;
		this.eventGroup = eventGroup;
		this.eventType = eventType;
		this.name = name;
		this.createUser = createUser;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.tag = tag;
		this.state = state;
		this.actionState = actionState;
		this.actionDate = actionDate;
		this.eventBlackLists = eventBlackLists;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_layer_id")
	public Layer getLayer() {
		return this.layer;
	}

	public void setLayer(Layer layer) {
		this.layer = layer;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_event_group_id", nullable = true)
	public EventGroup getEventGroup() {
		return this.eventGroup;
	}

	public void setEventGroup(EventGroup eventGroup) {
		this.eventGroup = eventGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_event_type_id", nullable = true)
	public EventType getEventType() {
		return this.eventType;
	}

	public void setEventType(EventType eventType) {
		this.eventType = eventType;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_state_id", nullable = false)
	public State getState() {
		return this.state;
	}

	public void setState(State state) {
		this.state = state;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_action_state_id", nullable = false)
	@org.hibernate.annotations.ColumnDefault("1")
	public ActionState getActionState() {
		return this.actionState;
	}

	public void setActionState(ActionState actionState) {
		this.actionState = actionState;
	}
	
	

	@Column(name = "name", length = 256)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "create_user", length = 64)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "create_date", length = 29)
	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_date", length = 29)
	public Timestamp getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Timestamp updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "tag", length = 256)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}
	
	@Column(name = "action_date")
	public Timestamp getActionDate() {
		return actionDate;
	}
	
	public void setActionDate(Timestamp actionDate) {
		this.actionDate = actionDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "blackList")
	public Set<EventBlackList> getEventBlackLists() {
		return this.eventBlackLists;
	}

	public void setEventBlackLists(Set<EventBlackList> eventBlackLists) {
		this.eventBlackLists = eventBlackLists;
	}
	
	
}
