package com.imst.event.map.hibernate.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AlertEvent generated by hbm2java
 */
@Entity
@Table(name = "database_dump", schema = "public")
public class DatabaseDump implements java.io.Serializable {

	private Integer id;
	private Timestamp createDate;
	private String name;
	private String key;
	private String dumpSize;
	
	public DatabaseDump() {
	}

	public DatabaseDump(Timestamp createDate, String name, String key, String dumpSize) {
		this.createDate = createDate;
		this.name = name;
		this.key = key;
		this.dumpSize = dumpSize;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "create_date", length = 29)
	@org.hibernate.annotations.ColumnDefault("now()")
	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}
	
	@Column(name = "key", unique = true, nullable = false, length = 14)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}
	
	@Column(name = "dump_size", unique = false, nullable = true, length = 32)
	public String getDumpSize() {
		return dumpSize;
	}

	public void setDumpSize(String dumpSize) {
		this.dumpSize = dumpSize;
	}

}
