package com.imst.event.map.hibernate.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Layer generated by hbm2java
 */
@Entity
@Table(name = "events_time_count", schema = "public")
public class EventsTimeCount implements java.io.Serializable{

	private Integer id;
	
	private Layer layer;
	private EventGroup eventGroup;
	private Long eventCount;
	
	private Integer eventDay;
	private Integer eventMonth;
	private Integer eventYear;
	
	public EventsTimeCount() {
		
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@Column(name = "event_count", nullable = false)
	public Long getEventCount() {
		return this.eventCount;
	}

	public void setEventCount(Long eventCount) {
		this.eventCount = eventCount;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_layer_id", nullable = false)
	public Layer getLayer() {
		return this.layer;
	}

	public void setLayer(Layer layer) {
		this.layer = layer;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_event_group_id", nullable = false)
	public EventGroup getEventGroup() {
		return this.eventGroup;
	}

	public void setEventGroup(EventGroup eventGroup) {
		this.eventGroup = eventGroup;
	}
	
	
	@Column(name = "event_day", nullable = false)
	public Integer getEventDay() {
		return this.eventDay;
	}

	public void setEventDay(Integer eventDay) {
		this.eventDay = eventDay;
	}
	
	
	@Column(name = "event_month", nullable = false)
	public Integer getEventMonth() {
		return this.eventMonth;
	}

	public void setEventMonth(Integer eventMonth) {
		this.eventMonth = eventMonth;
	}


	@Column(name = "event_year", nullable = false)
	public Integer getEventYear() {
		return eventYear;
	}


	public void setEventYear(Integer eventYear) {
		this.eventYear = eventYear;
	}
	
	
	

}
