package com.imst.event.map.hibernate.entity;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EventTag generated by hbm2java
 */
@Entity
@Table(name = "event_black_list")
public class EventBlackList implements java.io.Serializable {

	private Integer id;
	private Event event;
	private BlackList blackList;

	public EventBlackList() {
	}

	public EventBlackList(Event event, BlackList blackList) {
		this.event = event;
		this.blackList = blackList;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_event_id", nullable = false)
	public Event getEvent() {
		return this.event;
	}

	public void setEvent(Event event) {
		this.event = event;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_black_list_id", nullable = false)
	public BlackList getBlackList() {
		return this.blackList;
	}

	public void setBlackList(BlackList blackList) {
		this.blackList = blackList;
	}

}
