package com.imst.event.map.hibernate.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BlackList generated by hbm2java
 */
@Entity
@Table(name = "event_link", schema = "public")
public class EventLink implements java.io.Serializable{

	private Integer id;
	private EventColumn eventColumn;
	private String link;
	private String displayName;
	private String color;
	private Timestamp createDate;
	private Timestamp updateDate;
	
	
	public EventLink() {
		
	}
	
	public EventLink(Integer id, EventColumn eventColumn, String link, String displayName, String color, Timestamp createDate, Timestamp updateDate) {
		super();
		this.id = id;
		this.eventColumn = eventColumn;
		this.link = link;
		this.displayName = displayName;
		this.color = color;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_event_column_id", nullable = false)
	public EventColumn getEventColumn() {
		return this.eventColumn;
	}

	public void setEventColumn(EventColumn eventColumn) {
		this.eventColumn = eventColumn;
	}
	
	
	@Column(name = "link", nullable = false, length = 2048)
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "display_name", nullable = false, length = 128)
	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "color",nullable = false)
	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}
	
	@Column(name = "create_date", length = 29)
	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_date", length = 29)
	public Timestamp getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Timestamp updateDate) {
		this.updateDate = updateDate;
	}

	
}
