package com.imst.event.map.hibernate.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Settings generated by hbm2java
 */
@Entity
@Table(name="event_column", schema="public")
public class EventColumn implements java.io.Serializable{

	private Integer id;
	private String name;
	
	private Set<EventLink> eventLinks = new HashSet<EventLink>(0);
	
	public EventColumn() {
		
	}
	
	public EventColumn(Integer id, String name, Set<EventLink> eventLinks) {
		super();
		this.id = id;
		this.name = name;
		this.eventLinks = eventLinks;
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	
	
	@Column(name = "name", length = 2048)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eventColumn")
	public Set<EventLink> getEventLinks() {
		return this.eventLinks;
	}

	public void setEventLinks(Set<EventLink> eventLinks) {
		this.eventLinks = eventLinks;
	}

	
}
