package com.imst.event.map.hibernate.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * EventGroup generated by hbm2java
 */
@Entity
@Table(name = "event_group", uniqueConstraints = @UniqueConstraint(columnNames = { "fk_layer_id",
		"name" }))
public class EventGroup implements java.io.Serializable {

	private Integer id;
	private Layer layer;
	private String name;
	private String color;
	private String description;
	private Integer parentId;
	private Set<Event> events = new HashSet<Event>(0);
	private Set<Alert> alerts = new HashSet<Alert>(0);
	private Set<UserEventGroupPermission> userEventGroupPermissions = new HashSet<UserEventGroupPermission>(0);

	public EventGroup() {
	}

	public EventGroup(Layer layer, String name, String color, String description) {
		this.layer = layer;
		this.name = name;
		this.color = color;
		this.description = description;
	}

	public EventGroup(Layer layer, String name, String color, Set<Event> events, Set<Alert> alerts) {
		this.layer = layer;
		this.name = name;
		this.color = color;
		this.events = events;
		this.alerts = alerts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_layer_id", nullable = false)
	public Layer getLayer() {
		return this.layer;
	}

	public void setLayer(Layer layer) {
		this.layer = layer;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "color", nullable = false, length = 16)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "description", nullable = true, columnDefinition = "TEXT")
	public String getDescription() {
		return this.description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eventGroup")
	public Set<Event> getEvents() {
		return this.events;
	}

	public void setEvents(Set<Event> events) {
		this.events = events;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eventGroup")
	public Set<Alert> getAlerts() {
		return this.alerts;
	}

	public void setAlerts(Set<Alert> alerts) {
		this.alerts = alerts;
	}

	@Column(name = "parent_id", nullable = true)
	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eventGroup")
	public Set<UserEventGroupPermission> getUserEventGroupPermissions() {
		return this.userEventGroupPermissions;
	}

	public void setUserEventGroupPermissions(Set<UserEventGroupPermission> userEventGroupPermissions) {
		this.userEventGroupPermissions = userEventGroupPermissions;
	}
	
}
