package com.imst.event.map.hibernate.entity;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LayerExport generated by hbm2java
 */
@Entity
@Table(name = "layer_export", schema = "public")
public class LayerExport implements java.io.Serializable {

	private Integer id;
	private Layer layer;
	private Integer minZ;
	private Integer maxZ;
	private Timestamp createDate;
	private Timestamp startDate;
	private Timestamp finishDate;
	private Timestamp tileCreateDate;
	private Timestamp eventCreateDate;
	private String name;
	private TileServer tileServer;
	private Integer eventExportCount;

	public LayerExport() {
	}

	public LayerExport(Integer minZ, Integer maxZ, Timestamp createDate) {
		this.minZ = minZ;
		this.maxZ = maxZ;
		this.createDate = createDate;
	}

	public LayerExport(Layer layer, Integer minZ, Integer maxZ, Timestamp createDate, Timestamp startDate,
			Timestamp finishDate, Timestamp tileCreateDate, Timestamp eventCreateDate, String name, TileServer tileServer, Integer eventExportCount) {
		this.layer = layer;
		this.minZ = minZ;
		this.maxZ = maxZ;
		this.createDate = createDate;
		this.startDate = startDate;
		this.finishDate = finishDate;
		this.tileCreateDate = tileCreateDate;
		this.eventCreateDate = eventCreateDate;
		this.name = name;
		this.tileServer = tileServer;
		this.eventExportCount = eventExportCount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_layer_id")
	public Layer getLayer() {
		return this.layer;
	}

	public void setLayer(Layer layer) {
		this.layer = layer;
	}

	@Column(name = "min_z", nullable = false)
	public Integer getMinZ() {
		return this.minZ;
	}

	public void setMinZ(Integer minZ) {
		this.minZ = minZ;
	}

	@Column(name = "max_z", nullable = false)
	public Integer getMaxZ() {
		return this.maxZ;
	}

	public void setMaxZ(Integer maxZ) {
		this.maxZ = maxZ;
	}

	@Column(name = "create_date", nullable = false, length = 29)
	@org.hibernate.annotations.ColumnDefault("now()")
	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	@Column(name = "start_date", length = 29)
	public Timestamp getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Timestamp startDate) {
		this.startDate = startDate;
	}

	@Column(name = "finish_date", length = 29)
	public Timestamp getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Timestamp finishDate) {
		this.finishDate = finishDate;
	}

	@Column(name = "tile_create_date", length = 29)
	public Timestamp getTileCreateDate() {
		return tileCreateDate;
	}

	public void setTileCreateDate(Timestamp tileCreateDate) {
		this.tileCreateDate = tileCreateDate;
	}

	@Column(name = "event_create_date", length = 29)
	public Timestamp getEventCreateDate() {
		return eventCreateDate;
	}

	public void setEventCreateDate(Timestamp eventCrateDate) {
		this.eventCreateDate = eventCrateDate;
	}

	@Column(name = "name", length = 256)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_tile_server_id")
	public TileServer getTileServer() {
		return tileServer;
	}

	public void setTileServer(TileServer tileServer) {
		this.tileServer = tileServer;
	}

	@Column(name="event_export_count")
	public Integer getEventExportCount() {
		return eventExportCount;
	}

	public void setEventExportCount(Integer eventExportCount) {
		this.eventExportCount = eventExportCount;
	}
	
	

}
