package com.imst.event.map.hibernate.entity;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "log", schema = "public")
public class Log implements java.io.Serializable {

	private Integer id;
	private String username;
	private Integer userId;
	private String ip;
	private String description;
	private Timestamp createDate;
	private Integer fkLogTypeId;
	private Integer uniqueId;
	private String searchableDescription;

	public Log() {
	}

	public Log(String username, Integer userId, String ip, String description, Timestamp createDate,
			Integer fkLogTypeId, Integer uniqueId, String searchableDescription) {
		this.username = username;
		this.userId = userId;
		this.ip = ip;
		this.description = description;
		this.createDate = createDate;
		this.fkLogTypeId = fkLogTypeId;
		this.uniqueId = uniqueId;
		this.searchableDescription = searchableDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "username", length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "ip", length = 64)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "create_date", length = 29)
	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	@Column(name = "fk_log_type_id")
	public Integer getFkLogTypeId() {
		return this.fkLogTypeId;
	}

	public void setFkLogTypeId(Integer fkLogTypeId) {
		this.fkLogTypeId = fkLogTypeId;
	}

	@Column(name = "unique_id")
	public Integer getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(Integer uniqueId) {
		this.uniqueId = uniqueId;
	}

	@Column(name = "searchable_description")
	public String getSearchableDescription() {
		return this.searchableDescription;
	}

	public void setSearchableDescription(String searchableDescription) {
		this.searchableDescription = searchableDescription;
	}

}
