package com.imst.event.map.hibernate.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LogType generated by hbm2java
 */
@Entity
@Table(name = "log_type", schema = "public")
public class LogType implements java.io.Serializable {

	private Integer id;
	private String name;
	private String relatedTable;

	public LogType() {
	}

	public LogType(Integer id) {
		this.id = id;
	}

	public LogType(Integer id, String name, String relatedTable) {
		this.id = id;
		this.name = name;
		this.relatedTable = relatedTable;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "related_table", length = 64)
	public String getRelatedTable() {
		return this.relatedTable;
	}

	public void setRelatedTable(String relatedTable) {
		this.relatedTable = relatedTable;
	}

}
