package com.imst.event.map.hibernate.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MapAreaGroup generated by hbm2java
 */
@Entity
@Table(name = "map_area_group", schema = "public")
public class MapAreaGroup implements java.io.Serializable {

	private Integer id;
	private Layer layer;
	private String name;
	private String color;
	private Set<MapArea> mapAreas = new HashSet<MapArea>(0);

	public MapAreaGroup() {
	}

	public MapAreaGroup(Layer layer, String name, String color) {
		this.layer = layer;
		this.name = name;
		this.color = color;
	}

	public MapAreaGroup(Layer layer, String name, String color, Set<MapArea> mapAreas) {
		this.layer = layer;
		this.name = name;
		this.color = color;
		this.mapAreas = mapAreas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_layer_id", nullable = false)
	public Layer getLayer() {
		return this.layer;
	}

	public void setLayer(Layer layer) {
		this.layer = layer;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "color", nullable = false, length = 16)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mapAreaGroup")
	public Set<MapArea> getMapAreas() {
		return this.mapAreas;
	}

	public void setMapAreas(Set<MapArea> mapAreas) {
		this.mapAreas = mapAreas;
	}

}
