package com.imst.event.map.hibernate.entity;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MapArea generated by hbm2java
 */
@Entity
@Table(name = "map_area", schema = "public")
public class MapArea implements java.io.Serializable {

	private Integer id;
	private MapAreaGroup mapAreaGroup;
	private String title;
	private String coordinateInfo;
	private Boolean state;
	private Timestamp createDate;
	private Timestamp updateDate;

	public MapArea() {
	}

	public MapArea(MapAreaGroup mapAreaGroup, String coordinateInfo) {
		this.mapAreaGroup = mapAreaGroup;
		this.coordinateInfo = coordinateInfo;
	}

	public MapArea(MapAreaGroup mapAreaGroup, String title, String coordinateInfo, Boolean state, Timestamp createDate,
			Timestamp updateDate) {
		this.mapAreaGroup = mapAreaGroup;
		this.title = title;
		this.coordinateInfo = coordinateInfo;
		this.state = state;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_map_area_group_id", nullable = false)
	public MapAreaGroup getMapAreaGroup() {
		return this.mapAreaGroup;
	}

	public void setMapAreaGroup(MapAreaGroup mapAreaGroup) {
		this.mapAreaGroup = mapAreaGroup;
	}

	@Column(name = "title", length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "coordinate_info", nullable = false, columnDefinition = "TEXT")
	public String getCoordinateInfo() {
		return this.coordinateInfo;
	}

	public void setCoordinateInfo(String coordinateInfo) {
		this.coordinateInfo = coordinateInfo;
	}

	@Column(name = "state")
	@org.hibernate.annotations.ColumnDefault("true")
	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	@Column(name = "create_date", length = 29)
	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_date", length = 29)
	public Timestamp getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Timestamp updateDate) {
		this.updateDate = updateDate;
	}

}
