package com.imst.event.map.hibernate.entity;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", schema = "public")
public class Permission implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Boolean state;
	private String groupName;
	private Integer displayOrder;
	private Set<ProfilePermission> profilePermissions = new HashSet<ProfilePermission>(0);


	public Permission() {
	}

	public Permission(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	public Permission(Integer id, String name, String description, Boolean state, String groupName,
			Integer displayOrder, Set<ProfilePermission> profilePermissions) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.state = state;
		this.groupName = groupName;
		this.displayOrder = displayOrder;
		this.profilePermissions = profilePermissions;
		
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "state")
	public Boolean getState() {
		return this.state;
	}

	public void setState(Boolean state) {
		this.state = state;
	}

	@Column(name = "group_name", length = 64)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "display_order")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "permission")
	public Set<ProfilePermission> getProfilePermissions() {
		return this.profilePermissions;
	}

	public void setProfilePermissions(Set<ProfilePermission> profilePermissions) {
		this.profilePermissions = profilePermissions;
	}

}
