package com.imst.event.map.hibernate.entity;

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", schema = "public")
public class Profile implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Timestamp createDate;
	private Timestamp updateDate;
	private Boolean isDefault;
	private Set<ProfilePermission> profilePermissions = new HashSet<ProfilePermission>(0);
	private Set<User> users = new HashSet<User>(0);

	public Profile() {
	}

	public Profile(String name) {
		this.name = name;
	}

	public Profile(String name, String description, Timestamp createDate, Timestamp updateDate, Boolean isDefault,
			Set<ProfilePermission> profilePermissions, Set<User> users) {
		this.name = name;
		this.description = description;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.isDefault = isDefault;
		this.profilePermissions = profilePermissions;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 512)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "create_date", length = 29)
	public Timestamp getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Timestamp createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_date", length = 29)
	public Timestamp getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Timestamp updateDate) {
		this.updateDate = updateDate;
	}
	
	@Column(name = "is_default")
	public Boolean getIsDefault() {
		return isDefault;
	}
	
	public void setIsDefault(Boolean isDefault) {
		this.isDefault = isDefault;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<ProfilePermission> getProfilePermissions() {
		return this.profilePermissions;
	}

	public void setProfilePermissions(Set<ProfilePermission> profilePermissions) {
		this.profilePermissions = profilePermissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}
	
	

}
