package com.imst.event.map.hibernate.entity;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "spring_session", schema = "public")
public class SpringSession implements java.io.Serializable {

	private String primaryId;
	private String sessionId;
	private Long creationTime;
	private Long lastAccessTime;
	private Integer maxInactiveInterval;
	private Long expiryTime;
	private String principalName;
	private Set<SpringSessionAttributes> springSessionAttributes = new HashSet<SpringSessionAttributes>(0);

	public SpringSession() {
	}

	public SpringSession(String primaryId, String sessionId, Long creationTime, Long lastAccessTime, Integer maxInactiveInterval,
			Long expiryTime, String principalName) {
		this.primaryId = primaryId;
		this.sessionId = sessionId;
		this.creationTime = creationTime;
		this.lastAccessTime = lastAccessTime;
		this.maxInactiveInterval = maxInactiveInterval;
		this.expiryTime = expiryTime;
		this.principalName = principalName;
		
	}

	@Id

	@Column(name = "primary_id", unique = true, nullable = false, length = 36)
	public String getPrimaryId() {
		return this.primaryId;
	}

	public void setPrimaryId(String primaryId) {
		this.primaryId = primaryId;
	}

	@Column(name = "session_id", nullable = false, length = 36)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "creation_time", nullable = false)
	public Long getCreationTime() {
		return this.creationTime;
	}

	public void setCreationTime(Long creationTime) {
		this.creationTime = creationTime;
	}

	@Column(name = "last_access_time", nullable = false)
	public Long getLastAccessTime() {
		return this.lastAccessTime;
	}

	public void setLastAccessTime(Long lastAccessTime) {
		this.lastAccessTime = lastAccessTime;
	}

	@Column(name = "max_inactive_interval", nullable = false)
	public Integer getMaxInactiveInterval() {
		return this.maxInactiveInterval;
	}

	public void setMaxInactiveInterval(Integer maxInactiveInterval) {
		this.maxInactiveInterval = maxInactiveInterval;
	}

	@Column(name = "expiry_time", nullable = false)
	public Long getExpiryTime() {
		return this.expiryTime;
	}

	public void setExpiryTime(Long expiryTime) {
		this.expiryTime = expiryTime;
	}
	
	@Column(name = "principal_name", length = 100)
	public String getPrincipalName() {
		return this.principalName;
	}

	public void setPrincipalName(String principalName) {
		this.principalName = principalName;
	}
	
	@OnDelete(action = OnDeleteAction.CASCADE)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sessionPrimaryId", cascade=CascadeType.REMOVE)
	public Set<SpringSessionAttributes> getSpringSessionAttributes() {
		return this.springSessionAttributes;
	}

	public void setSpringSessionAttributes(Set<SpringSessionAttributes> springSessionAttributes) {
		this.springSessionAttributes = springSessionAttributes;
	}

}
