package com.imst.event.map.hibernate.entity;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "spring_session_attributes", schema = "public")
public class SpringSessionAttributes implements java.io.Serializable {

	private SpringSession sessionPrimaryId;
	private String attributeName;
	private byte[] attributeBytes;

	public SpringSessionAttributes() {
	}

	public SpringSessionAttributes(SpringSession sessionPrimaryId, String attributeName, byte[] attributeBytes) {
		this.sessionPrimaryId = sessionPrimaryId;
		this.attributeName = attributeName;
		this.attributeBytes = attributeBytes;
		
	}

	@Id
	@OnDelete(action = OnDeleteAction.CASCADE)
	@ManyToOne(fetch = FetchType.LAZY, cascade=CascadeType.REMOVE)
	@JoinColumn(name = "session_primary_id", nullable = false)
//	@Column(name = "session_primary_id", nullable = false, length = 36)
	public SpringSession getSessionPrimaryId() {
		return this.sessionPrimaryId;
	}

	public void setSessionPrimaryId(SpringSession sessionPrimaryId) {
		this.sessionPrimaryId = sessionPrimaryId;
	}

	@Id
	@Column(name = "attribute_name", nullable = false, length = 200)
	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}
	
	@Column(name = "attribute_bytes", nullable = false)
	public byte[] getAttributeBytes() {
		return this.attributeBytes;
	}

	public void setAttributeBytes(byte[] attributeBytes) {
		this.attributeBytes = attributeBytes;
	}

}
